---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: internal-apps
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/headlamp/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: internal-apps
spec:
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: headlamp
  interval: 1m0s
  values:
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 100
      runAsGroup: 101
      fsGroup: 101
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      readOnlyRootFilesystem: false
      seccompProfile:
        type: RuntimeDefault
    ingress:
      enabled: true
      ingressClassName: traefik-internal
      hosts:
        - host: headlamp.dev.home
          paths:
            - path: /
              type: ImplementationSpecific
    config:
      pluginsDir: /build/plugins
      extraArgs:
        - -oidc-ca-file=/etc/ssl/certs/jabbas-ca.crt
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: oidc-secret-headlamp
    initContainers:
      - name: headlamp-plugins
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 100
          runAsGroup: 101
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    env:
      - name: SSL_CERT_FILE
        value: /etc/ssl/certs/jabbas-ca.crt
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
      - mountPath: /etc/ssl/certs/jabbas-ca.crt
        name: jabbas-ca
        subPath: ca.crt
        readOnly: true
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
      - name: jabbas-ca
        secret:
          secretName: jabbas-ca
