---
# Pull-based Reflector mirror for Headlamp OIDC credentials
# Source: authentik/authentik-stack-oidc-headlamp
apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret-headlamp
  namespace: internal-apps
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: authentik/authentik-stack-oidc-headlamp
type: Opaque
data: {}
